#!/bin/bash

#
# uploadnewip by github.com/Boby_MC_bobs
# Project licensed under GPL3, have fun.
#

# v1

#configs edited initally by install.sh
purpose_name=''
dbFolder=''
loopDelayTime=''
ping_server=''
scriptsFolder=''
fetch_ip_server='ipinfo.io/ip'

serverIPFolder="$scriptsFolder/uploadnewip/"
tempIPPos="$serverIPFolder/temp-ip-$purpose_name.txt"
currentIPPos="$serverIPFolder/currentip-$purpose_name.txt"

first_var=$1

if [ $purpose_name = "" ] && [ $dbFolder = "" ] && [ $loopDelayTime = "" ] && [ $ping_server = "" ] && [ $scriptsFolder = "" ]
then
	echo "> Script not configured. Please run './install.sh'."
	exit
fi

echo "> Program Initalising."

function required_stuff() {
	#install and fix dropbox uploader, and the select dropbox folder
	if [ ! -f $scriptsFolder/dropbox_uploader.sh ]
	then
		echo "> '$scriptsFolder/dropbox_uploader.sh' not found. Downloading."
		ping_test
		if curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" -o $scriptsFolder/dropbox_uploader.sh > /dev/null
		then
			echo "> Download Complete."
			chmod +x $scriptsFolder/dropbox_uploader.sh
		else
			echo "> Download Failed."
			if [ -f $scriptsFolder/dropbox_uploader.sh ]
			then
				rm $scriptsFolder/dropbox_uploader.sh
			fi
			required_stuff
		fi
	fi

	if ! $scriptsFolder/dropbox_uploader.sh list | grep -w $dbFolder > /dev/null
	then
		echo "> Dropbox folder '$dbFolder' not found. Creating it."
		$scriptsFolder/dropbox_uploader.sh mkdir $dbFolder
	fi
}

function main() {
	#main routine
	ping_test
	if [ $net = 0 ]
	then
		echo "> Checking against fresh IP from ipinfo.io"

		rm $tempIPPos
		curl $fetch_ip_server > $tempIPPos

		echo "> Verifying"

		chk1=$(sha256sum $tempIPPos | awk '{print $1}')
		chk2=$(sha256sum $currentIPPos | awk '{print $1}')

		if [ "$chk1" == "$chk2" ]
		then
			#hasn't changed
			echo "> IP hasn't changed."
		else
			#has changed
			echo "> IP has changed."
			successful
		fi

		if [[ $first_var = "-n" ]]
		then
			echo "> Updating anyways"
			successful
		fi

	else
		echo "> Since there is no internet connection, we're not gonna try uploading."
	fi
}

function ping_test() {
	#test internet
	echo "> Running a quick ping test to '$ping_server' to test internet."
	if ping -q -c 1 -W 1 $ping_server > /dev/null
	then
	  	#if internet is up
		echo "> Internet is connected, continuing."
		net=0

	else
	  	#if internet is down
		echo "> No internet."
		net=1
	fi
}

function successful() {
	#upload to dropbox.
	echo "> Updaing DropBox files..."
	cat $tempIPPos > $currentIPPos
	echo "> Removing old IP file..."
	if $scriptsFolder/dropbox_uploader.sh list /$dbFolder/ | grep -w currentip-$purpose_name.txt
	then
		$scriptsFolder/dropbox_uploader.sh delete /$dbFolder/currentip-$purpose_name.txt
	fi
	echo "> Uploading 'currentip-$purpose_name.txt' to Dropbox."
	$scriptsFolder/dropbox_uploader.sh upload $serverIPFolder/currentip-$purpose_name.txt /$dbFolder/
	date=$(date)
	ipf=$(cat currentip-$purpose_name.txt)
	theip=$(curl ipinfo.io/ip)
	echo "ServerIP updated to $theip at $date (automatically)." | tee -a $serverIPFolder/serveripupdate.log
}

required_stuff

#loop main function
while true
do
	main
	echo "> Now waiting $loopDelayTime seconds."
	sleep $loopDelayTime$(echo s)
done
